# EDA On Mobile Price Prediction Data Analysis

#### Predict a price range, indicating how high the price of the moible is 

- Here we have build the model using Logistic regression and KNN and we can conculde that Logistic regression gives us a good accuracy compared to KNN model

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')
pd.set_option("display.max_columns",None)

In [3]:
mobile_proj=pd.read_csv(r"C:\Users\Admin\Downloads\Mobile_data.csv",)

In [4]:
mobile_proj.head()

battery_power  clock_speed  fc  int_memory  m_dep  mobile_wt  n_cores  pc  \
0            842          2.2   1           7    0.6        188        2   2   
1           1021          0.5   0          53    0.7        136        3   6   
2            563          0.5   2          41    0.9        145        5   6   
3            615          2.5   0          10    0.8        131        6   9   
4           1821          1.2  13          44    0.6        141        2  14   

   px_height  px_width   ram  sc_h  sc_w  talk_time  price_range  
0         20       756  2549     9     7         19            1  
1        905      1988  2631    17     3          7            2  
2       1263      1716  2603    11     2          9            2  
3       1216      1786  2769    16     8         11            2  
4       1208      1212  1411     8     2         15            1

In [5]:
mobile_proj.shape

(2000, 15)

In [6]:
mobile_proj.describe(include='all')

battery_power  clock_speed           fc   int_memory        m_dep  \
count    2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     1.522250     4.309500    32.046500     0.501750   
std       439.418206     0.816004     4.341444    18.145715     0.288416   
min       501.000000     0.500000     0.000000     2.000000     0.100000   
25%       851.750000     0.700000     1.000000    16.000000     0.200000   
50%      1226.000000     1.500000     3.000000    32.000000     0.500000   
75%      1615.250000     2.200000     7.000000    48.000000     0.800000   
max      1998.000000     3.000000    19.000000    64.000000     1.000000   

         mobile_wt      n_cores           pc    px_height     px_width  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    140.249000     4.520500     9.916500   645.108000  1251.515500   
std      35.399655     2.287837     6.064315   443.780811   432.199447   
min      80.000000     1.000000     0.000000     0.000000   500.000000   
25%     109.000000     3.000000     5.000000   282.750000   874.750000   
50%     141.000000     4.000000    10.000000   564.000000  1247.000000   
75%     170.000000     7.000000    15.000000   947.250000  1633.000000   
max     200.000000     8.000000    20.000000  1960.000000  1998.000000   

               ram         sc_h         sc_w    talk_time  price_range  
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  
mean   2124.213000    12.306500     5.767000    11.011000     1.500000  
std    1084.732044     4.213245     4.356398     5.463955     1.118314  
min     256.000000     5.000000     0.000000     2.000000     0.000000  
25%    1207.500000     9.000000     2.000000     6.000000     0.750000  
50%    2146.500000    12.000000     5.000000    11.000000     1.500000  
75%    3064.500000    16.000000     9.000000    16.000000     2.250000  
max    3998.000000    19.000000    18.000000    20.000000     3.000000

## Pre Processing

In [7]:
#finding the missing values
print(mobile_proj.isnull().sum())

battery_power    0
clock_speed      0
fc               0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
price_range      0
dtype: int64


In [18]:
for i in mobile_proj.columns:
    print({i:mobile_proj[i].unique()})

{'battery_power': array([ 842, 1021,  563, ..., 1139, 1467,  858], dtype=int64)}
{'clock_speed': array([2.2, 0.5, 2.5, 1.2, 1.7, 0.6, 2.9, 2.8, 2.1, 1. , 0.9, 1.1, 2.6,
       1.4, 1.6, 2.7, 1.3, 2.3, 2. , 1.8, 3. , 1.5, 1.9, 2.4, 0.8, 0.7])}
{'fc': array([ 1,  0,  2, 13,  3,  4,  5,  7, 11, 12, 16,  6, 15,  8,  9, 10, 18,
       17, 14, 19], dtype=int64)}
{'int_memory': array([ 7, 53, 41, 10, 44, 22, 24,  9, 33, 17, 52, 46, 13, 23, 49, 19, 39,
       47, 38,  8, 57, 51, 21,  5, 60, 61,  6, 11, 50, 34, 20, 27, 42, 40,
       64, 14, 63, 43, 16, 48, 12, 55, 36, 30, 45, 29, 58, 25,  3, 54, 15,
       37, 31, 32,  4, 18,  2, 56, 26, 35, 59, 28, 62], dtype=int64)}
{'m_dep': array([0.6, 0.7, 0.9, 0.8, 0.1, 0.5, 1. , 0.3, 0.4, 0.2])}
{'mobile_wt': array([188, 136, 145, 131, 141, 164, 139, 187, 174,  93, 182, 177, 159,
       198, 185, 196, 121, 101,  81, 156, 199, 114, 111, 132, 143,  96,
       200,  88, 150, 107, 100, 157, 160, 119,  87, 152, 166, 110, 118,
       162, 127, 109, 102, 104, 

#### Insights: Here we can observe that there is no missing values in this data


In [8]:
mobile_proj.dtypes

battery_power      int64
clock_speed      float64
fc                 int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
price_range        int64
dtype: object

#### Insight: there are no catogrical values so there is no need of converstion

# Creating X and Y

In [9]:
x=mobile_proj.values[:,0:-1]
y=mobile_proj.values[:,-1]

In [10]:
x.shape

(2000, 14)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
x=scaler.fit_transform(x)
#scaler.fit(x)
#x=scaler.transform(x)
print(x)


[[-0.90259726  0.83077942 -0.76249466 ... -0.78498329  0.2831028
   1.46249332]
 [-0.49513857 -1.2530642  -0.99289039 ...  1.11426556 -0.63531667
  -0.73426721]
 [-1.5376865  -1.2530642  -0.53209893 ... -0.31017108 -0.86492153
  -0.36814045]
 ...
 [ 1.53077336 -0.76274805 -0.76249466 ... -0.78498329 -1.0945264
  -1.10039396]
 [ 0.62252745 -0.76274805 -0.07130748 ...  1.35167167  0.9719174
   1.46249332]
 [-1.65833069  0.58562134  0.15908825 ...  1.58907778 -0.4057118
  -1.6495841 ]]


# Building The Model

In [12]:
from sklearn.model_selection import train_test_split

#split the data into and train

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

In [19]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1600, 14)
(1600,)
(400, 14)
(400,)


In [21]:
#predicting using the Kneighbors_classifier

from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(x_train))),metric='manhattan')

#fit the  model on the data and predict the values
model_KNN.fit(x_train,y_train)

y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(3.0, 3.0), (3.0, 2.0), (2.0, 1.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (2.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 1.0), (3.0, 2.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 0.0), (2.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 1.0), (0.0, 0.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 2.0), (0.0, 1.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 0.0), (1.0, 2.0), (3.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 0.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.

In [22]:
import numpy as np
np.sqrt(len(x_train))

40.0

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)
print()

print("Classification report: ")

print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test, y_pred)
print("Accuracy of the model: ",acc)

[[80 12  0  0]
 [21 64 12  0]
 [ 1 25 70 13]
 [ 0  0 19 83]]

Classification report: 
              precision    recall  f1-score   support

         0.0       0.78      0.87      0.82        92
         1.0       0.63      0.66      0.65        97
         2.0       0.69      0.64      0.67       109
         3.0       0.86      0.81      0.84       102

    accuracy                           0.74       400
   macro avg       0.74      0.75      0.74       400
weighted avg       0.74      0.74      0.74       400

Accuracy of the model:  0.7425


# Tunning

In [25]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    model_KNN=KNeighborsClassifier(n_neighbors=K,metric='manhattan')
    model_KNN.fit(x_train,y_train)
    y_pred=model_KNN.predict(x_test)
    print("Accuracy is",accuracy_score(y_test,y_pred),'for K-Value:',K)
    my_dict[K]=accuracy_score(y_test,y_pred)

Accuracy is 0.53 for K-Value: 1
Accuracy is 0.4875 for K-Value: 2
Accuracy is 0.54 for K-Value: 3
Accuracy is 0.5775 for K-Value: 4
Accuracy is 0.615 for K-Value: 5
Accuracy is 0.625 for K-Value: 6
Accuracy is 0.64 for K-Value: 7
Accuracy is 0.68 for K-Value: 8
Accuracy is 0.6625 for K-Value: 9
Accuracy is 0.6825 for K-Value: 10
Accuracy is 0.695 for K-Value: 11
Accuracy is 0.7125 for K-Value: 12
Accuracy is 0.695 for K-Value: 13
Accuracy is 0.705 for K-Value: 14
Accuracy is 0.7075 for K-Value: 15
Accuracy is 0.71 for K-Value: 16
Accuracy is 0.715 for K-Value: 17
Accuracy is 0.72 for K-Value: 18
Accuracy is 0.7175 for K-Value: 19
Accuracy is 0.7325 for K-Value: 20
Accuracy is 0.7175 for K-Value: 21
Accuracy is 0.7175 for K-Value: 22
Accuracy is 0.7275 for K-Value: 23
Accuracy is 0.7325 for K-Value: 24
Accuracy is 0.7375 for K-Value: 25
Accuracy is 0.74 for K-Value: 26
Accuracy is 0.7475 for K-Value: 27
Accuracy is 0.74 for K-Value: 28
Accuracy is 0.7575 for K-Value: 29
Accuracy is 0.76

In [15]:
from sklearn.linear_model import LogisticRegression
#create a model 
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(x_train, y_train)

y_pred=classifier.predict(x_test)
print(list(zip(y_test,y_pred)))

[(3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (3.0, 2.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 1.0), (1.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 0.0), (0.

In [26]:
#to find the maximum of the value
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,':',my_dict[k])

30 : 0.765


In [27]:
#predicting using the Kneighbors_classifier

from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=30,metric='manhattan')

#fit the  model on the data and predict the values
model_KNN.fit(x_train,y_train)

y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(3.0, 3.0), (3.0, 2.0), (2.0, 1.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (3.0, 2.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (2.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 0.0), (2.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (0.0, 1.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (2.0, 2.0), (3.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 0.0), (1.0, 2.0), (3.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 0.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test, y_pred)
print("Accuracy of the model: ",acc)


[[ 92   0   0   0]
 [  2  94   1   0]
 [  0   5 102   2]
 [  0   0   3  99]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99        92
         1.0       0.95      0.97      0.96        97
         2.0       0.96      0.94      0.95       109
         3.0       0.98      0.97      0.98       102

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

Accuracy of the model:  0.9675


#### Insight: Here we can observe that base model even after tunning gives us almost the same accuarcy


# Logistic Regression

In [30]:
#Recreating X and Y
x=mobile_proj.values[:,0:-1]
y=mobile_proj.values[:,-1]

In [31]:
from sklearn.model_selection import train_test_split

#split the data into test and train
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [32]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1600, 14)
(1600,)
(400, 14)
(400,)


In [33]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [34]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier=LogisticRegression(multi_class='multinomial')
#train the model object
classifier.fit(x_train,y_train)# fit function is used to train the model

y_pred=classifier.predict(x_test)
print(list(zip(y_test,y_pred)))

[(3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (3.0, 2.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 1.0), (1.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 0.0), (0.

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test, y_pred)
print("Accuracy of the model: ",acc)

[[ 92   0   0   0]
 [  2  94   1   0]
 [  0   5 102   2]
 [  0   0   3  99]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99        92
         1.0       0.95      0.97      0.96        97
         2.0       0.96      0.94      0.95       109
         3.0       0.98      0.97      0.98       102

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

Accuracy of the model:  0.9675


#### Insight: So overall we can conclude that logistic regression works well when compared to KNN model
